library(phyloclim)

bio1_pno = pno(path_bioclim = "glomerulataclipped/BIOCLIM_1.asc", path_model = "glomerulatamodel/layerforpno/", bin_number = 50)
write.csv(bio1_pno, file = "glomerulata_pnos/bio1_pno.csv")
bio7_pno = pno(path_bioclim = "glomerulataclipped/BIOCLIM_7.asc", path_model = "glomerulatamodel/layerforpno/", bin_number = 50)
write.csv(bio7_pno, file = "glomerulata_pnos/bio7_pno.csv")
bio12_pno = pno(path_bioclim = "glomerulataclipped/BIOCLIM_12.asc", path_model = "glomerulatamodel/layerforpno/", bin_number = 50)
write.csv(bio12_pno, file = "glomerulata_pnos/bio12_pno.csv")
bio17_pno = pno(path_bioclim = "glomerulataclipped/BIOCLIM_17.asc", path_model = "glomerulatamodel/layerforpno/", bin_number = 50)
write.csv(bio17_pno, file = "glomerulata_pnos/bio17_pno.csv")
elevation_pno = pno(path_bioclim = "glomerulataclipped/GTOPO30_ELEVATION.asc", path_model = "glomerulatamodel/layerforpno/", bin_number = 50)
write.csv(elevation_pno, file = "glomerulata_pnos/elevation_pno.csv")
slope_pno = pno(path_bioclim = "glomerulataclipped/GTOPO30_SLOPE.asc", path_model = "glomerulatamodel/layerforpno/", bin_number = 50)
write.csv(slope_pno, file = "glomerulata_pnos/slope_pno.csv")

coarsefragment_pno = pno(path_bioclim = "glomerulataclipped/ISRICSOILGRIDS_average_coarsefragmentpercent.asc", path_model = "glomerulatamodel/layerforpno/", bin_number = 50)
write.csv(coarsefragment_pno, file = "glomerulata_pnos/coarsefragment_pno.csv")
ph_pno = pno(path_bioclim = "glomerulataclipped/ISRICSOILGRIDS_average_phx10.asc", path_model = "glomerulatamodel/layerforpno/", bin_number = 50)
write.csv(ph_pno, file = "glomerulata_pnos/ph_pno.csv")
sand_pno = pno(path_bioclim = "glomerulataclipped/ISRICSOILGRIDS_average_sandpercent.asc", path_model = "glomerulatamodel/layerforpno/", bin_number = 50)
write.csv(sand_pno, file = "glomerulata_pnos/sand_pno.csv")
carbon_pno = pno(path_bioclim = "glomerulataclipped/ISRICSOILGRIDS_average_soilorganiccarboncontent.asc", path_model = "glomerulatamodel/layerforpno/", bin_number = 50)
write.csv(carbon_pno, file = "glomerulata_pnos/carbon_pno.csv")


needle_pno = pno(path_bioclim = "glomerulataclipped/LandCover_1_Needleleaf.asc", path_model = "glomerulatamodel/layerforpno/", bin_number = 50)
write.csv(needle_pno, file = "glomerulata_pnos/needle_pno.csv")
herbaceous_pno = pno(path_bioclim = "glomerulataclipped/LandCover_6_Herbaceous.asc", path_model = "glomerulatamodel/layerforpno/", bin_number = 50)
write.csv(herbaceous_pno, file = "glomerulata_pnos/herbaceous_pno.csv")
